name = "indent-rainbow"
version = "0.0.1"
authors = ["Your Name <you@example.com>"]
description = "Adds rainbow colors to indentation levels."
repository = "https://github.com/yourusername/zed-indent-rainbow"

